Added AEGIS-256, libsodium/master, and fixed headers in openssl.c
mumble-voip/crypto-benchmark pull request #2
Opened 2020-05-05 17:23 UTC by Avatat

In this pull request, I added support for AEGIS-256 algorithm, which is implemented in libsodium library. To use this algorithm, it was needed to compile libsodium/master branch, because AEGIS-256 is not in stable branch nor releases.
I also did a minor fix in openssl.c header section.

I would like to thank @davidebeatrici for all help given to me through the developing process!

2020-05-05 18:55 UTC, davidebeatrici requested changes
Changes look almost perfect!

2020-05-05 18:55 UTC, davidebeatrici commented on .gitignore
> +/build
```suggestion
.idea
cmake-build-debug
build
```

I would also move this change to a separate commit, with a message like "Add .gitignore".

2020-05-05 18:55 UTC, davidebeatrici commented on .travis.yml
> +  - sudo apt-get install libnss3-dev libssl-dev libtool libwolfssl-dev
I see you adhered to the alphabetical order, which is absolutely fine.

However, I would put `libtool` at the beginning since it's a build tool.

2020-05-05 18:55 UTC, davidebeatrici commented on .travis.yml
> +  - cd libsodium && git checkout 88c568a03522cda6c54fd4b5c76cfbbc52a744f4 && ./autogen.sh && ./configure --enable-opt && make -j $(nproc) && make check && sudo make install && sudo ldconfig && cd ..
I would move the `git checkout` command under `before_install`.

Also, maybe the command should be split in multiple ones. I would do something like:

```bash
cd libsodium
./autogen.sh && ./configure --enable-opt
make -j $(nproc) && make check
sudo make install && sudo ldconfig
cd ..
```

2020-05-05 18:55 UTC, davidebeatrici commented on sodium.c
> +		CIPHER_AEGIS_256,
Right now the ciphers are ordered by popularity.

Should we perhaps order them alphabetically, instead?

2020-05-05 18:55 UTC, davidebeatrici commented on utils.h
> +#define CIPHER_AEGIS_256 "AEGIS-256"
I would put the new cipher at the beginning, to maintain alphabetical order.

2020-05-05 18:55 UTC, davidebeatrici commented on sodium.c
> +  } else {
Inconsistent indentation (spaces instead of tabs).

2020-05-05 18:55 UTC, davidebeatrici commented on sodium.c
> +			printf("sodium_encrypt(): ccrypto_aead_aegis256_encrypt_detached() failed!\n");
```suggestion
			printf("sodium_encrypt(): crypto_aead_aegis256_encrypt_detached() failed!\n");
```

2020-05-05 18:55 UTC, davidebeatrici commented on utils.h
> +#define IV_SIZE 32
This change was suggested by me, but it broke NSS because we set the buffer's size as IV length.

Maybe defining the sizes globally was not a good idea after all...

2020-05-05 20:09 UTC, Avatat commented on .gitignore
> +/build
I removed .gitignore from this pull request, and will prepare another :)

2020-05-05 20:10 UTC, Avatat commented on utils.h
> +#define IV_SIZE 32
I redefined IV_SIZE in sodium.h.

2020-05-05 20:12 UTC, Avatat commented
@davidebeatrici, thank you for the review! I corrected all the mentioned suggestions.

2020-05-06 05:20 UTC, Krzmbrzl approved these changes

2020-05-06 19:18 UTC, davidebeatrici approved these changes

2020-05-06 20:12 UTC, merged

2020-05-06 20:12 UTC, davidebeatrici commented
Thank you very much for your contribution!