Added ciphers comparison table to README
mumble-voip/crypto-benchmark pull request #6
Opened 2020-05-30 23:36 UTC by Avatat

2020-05-30 23:39 UTC, davidebeatrici commented on README.md
> +| ChaCha20-Poly1305 | wolfCrypt | GPLv2 |  |
Should we perhaps add "Optimizations disabled by default"?

wolfSSL/wolfssl#2691

2020-05-31 08:38 UTC, Avatat commented on README.md
> +| ChaCha20-Poly1305 | wolfCrypt | GPLv2 |  |
Done!

2020-05-31 17:52 UTC, davidebeatrici requested changes

2020-05-31 17:52 UTC, davidebeatrici commented on README.md
> +| AES-256-GCM | libsodium | ISC | [Requires SSSE3, AES-NI and CLMUL](https://doc.libsodium.org/secret-key_cryptography/aead/aes-256-gcm#limitations) |
```suggestion
| AES-256-GCM | libsodium | ISC | [Requires SSSE3 + `aesni` and `pclmul` instructions](https://doc.libsodium.org/secret-key_cryptography/aead/aes-256-gcm#limitations) |
```

2020-05-31 20:42 UTC, Avatat commented on README.md
> +| AES-256-GCM | libsodium | ISC | [Requires SSSE3, AES-NI and CLMUL](https://doc.libsodium.org/secret-key_cryptography/aead/aes-256-gcm#limitations) |
Fixed!

2020-05-31 20:43 UTC, davidebeatrici approved these changes

2020-05-31 20:58 UTC, davidebeatrici approved these changes

2020-05-31 21:16 UTC, merged